const express = require('express');
const router = express.Router();
const User = require('./models/User.js');
const Balance = require('./models/Balance.js');
const Crypto = require('./models/Crypto.js');

router.get('/', (req, res) => {
    res.json({ message: 'Hello, World!' });
});

router.post('/create-user', async (req, res) => {
    try {
        const { username, role } = req.body;

        const newUser = await User.create({
            username,
            role,
        });

        const newBalance = await Balance.create({
            user_id: newUser.user_id, // Assign the user_id generated by Sequelize
            crypto_balance: 0, // You can set the initial balance to 0 or another value
        });

        res.status(200).json({ newUser, newBalance }); // Respond with the created user
    } catch (error) {
        console.error('Error creating user:', error);
        res.status(500).json({ error: 'User creation failed' });
    }
});

router.post('/add-crypto', async (req, res) => {
    try {
        const { name, symbol } = req.body;

        const newCrypto = await Crypto.create({
            name, symbol,
        });

        res.status(200).json({ newCrypto })

    } catch (error) {
        console.error('Error creating crypto:', error)
        res.status(500).json({ error: 'Create crypto fail' });
    }
});

module.exports = router;
